# Makefile para scripts R

.PLONY: clean all

all:
	# shell
	sh shellscript/sedLatex/loadings.sh
	sh shellscript/sedLatex/briefFA.sh
	#sh ../shellscript/sedLatex/pmf.sh
	#sh ../shellscript/sedLatex/general.sh

	# Python
	#python ../python/edxCalibration_K.py
	#python ../python/edxCalibration_L.py

clean:
	rm -rf *~ 
