# Makefile para scripts R

.PLONY: clean all

all:
	# shell
	sh shellscript/sed_loadings.sh
	sh shellscript/sed.sh
	#sh ../shellscript/sed_pmf.sh

	# Python
	#python ../python/edxCalibration_K.py
	#python ../python/edxCalibration_L.py

clean:
	rm -rf *~ 
